[alias]
	b="build"
	c="check"
	d="doc"
	t="test"
	r="run"
	rr = "run --release"
	rm="remove"
	br="build --release"

# [build]
# rustflags = ["-C", "target-cpu=native"]
# rustflags = ["-Z", "threads=8"] # only with nightly compiler
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
